Feat/governance mvp ai (#12)
* feat(nx-governance): AI layer to Governance MVP

* docs(nx-governance): Added metrics interpretation sections

* chore: remove nx-governance run changes in package.json of other plugins

* chore(release): publish

- project: nx-governance 0.1.0

- project: nx-typeorm 0.0.3

- project: nx-js 0.0.3

* Potential fix for code scanning alert no. 2: Unsafe shell command constructed from library input

Co-authored-by: Copilot Autofix powered by AI <62310815+github-advanced-security[bot]@users.noreply.github.com>

* ci: fixed packages/governance/src/plugin/run-governance.ts:1886:7 - error TS2554: Expected 1-2 arguments, but got 3.